# fly.toml app configuration file generated for shopify-payment-customization-app on 2023-11-23T22:34:26+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shopify-payment-customization-app"
primary_region = "sin"

[build]

[env]
PORT = "8081"
SCOPES = "write_products,write_payment_customizations"
SHOPIFY_API_KEY = "1ff37070f0254c36ffdb5613230d1d71"
SHOPIFY_APP_URL = "https://shopify-payment-customization-app.fly.dev/"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8081
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
