api_version = "2023-10"

[[extensions]]
description = "t:description"
handle = "payment-customization"
name = "t:name"
type = "function"

[[extensions.targeting]]
export = "run"
input_query = "src/run.graphql"
target = "purchase.payment-customization.run"

[extensions.build]
command = ""
path = "dist/function.wasm"

[extensions.ui.paths]
create = "/app/payment-customization/:functionId/new"
details = "/app/payment-customization/:functionId/:id"
